name: Deploy Bot to Pterodactyl Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy files via SFTP
      run: |
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        mirror --reverse --delete --verbose --exclude .git --exclude .npm --exclude node_modules --only-newer ./ ./
        bye
        "
    - name: Create .env file on server
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
        echo "PTERODACTYL_API_KEY=${{ secrets.PTERODACTYL_API_KEY }}" >> .env
        echo "PTERODACTYL_SERVER_ID=${{ secrets.PTERODACTYL_SERVER_ID }}" >> .env
        echo "PTERODACTYL_BASE_URL=${{ secrets.PTERODACTYL_BASE_URL }}" >> .env
        echo "ADMIN_USERS=${{ secrets.ADMIN_USERS }}" >> .env
        echo "PZ_SERVER_IP=${{ secrets.SERVER_IP }}" >> .env
        echo "PZ_SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> .env
        echo "LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}" >> .env
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        put -O ./ ./.env
        bye
        "
    - name: Trigger server restart
      run: |
        curl --location "${{ secrets.DISCORD_PTERODACTYL_API_POWER_URL }}" \
        --header 'Content-Type: application/json' \
        --header "Authorization: Bearer ${{ secrets.DISCORD_PTERODACTYL_API_BEARER_TOKEN }}" \
        --data '{
          "signal": "restart"
        }'