name: Deploy Bot to Pterodactyl Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp and zip
      run: |
        sudo apt-get install lftp zip

    - name: Create ZIP file
      run: |
        zip -r bot.zip . -x ".git/*"

    - name: Deploy ZIP file via SFTP
      run: |
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        put bot.zip -o ./bot.zip
        bye
        "

    - name: Extract ZIP file on server
      run: |
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        !unzip -o ./bot.zip -d .
        !rm ./bot.zip
        bye
        "

    - name: Create .env file on server
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
        echo "PTERODACTYL_API_KEY=${{ secrets.PTERODACTYL_API_KEY }}" >> .env
        echo "PTERODACTYL_SERVER_ID=${{ secrets.PTERODACTYL_SERVER_ID }}" >> .env
        echo "PTERODACTYL_BASE_URL=${{ secrets.PTERODACTYL_BASE_URL }}" >> .env
        echo "ADMIN_USERS=${{ secrets.ADMIN_USERS }}" >> .env
        echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> .env
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> .env
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        put -O ./ ./.env
        bye
        "
