name: Deploy Bot to Pterodactyl Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy files via SFTP
      run: |
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        mirror --reverse --delete --verbose ./ ./
        bye
        "

    - name: Create .env file on server
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
        echo "PTERODACTYL_API_KEY=${{ secrets.PTERODACTYL_API_KEY }}" >> .env
        echo "PTERODACTYL_SERVER_ID=${{ secrets.PTERODACTYL_SERVER_ID }}" >> .env
        echo "PTERODACTYL_BASE_URL=${{ secrets.PTERODACTYL_BASE_URL }}" >> .env
        echo "ADMIN_USERS=${{ secrets.ADMIN_USERS }}" >> .env
        echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> .env
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> .env
        lftp -e "
        set sftp:auto-confirm yes
        open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_URL }}
        put -O ./ ./.env
        bye
        "
